config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "movies#index"
  resources :lists do
    resources :bookmarks
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
    belongs_to :movie
    belongs_to :list

    validates :comment, presence: true, length: { minimum: 6 }
    validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
  has_many_attached :photos
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, presence:true
  validates :name, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
    has_many :bookmarks
    has_many :lists, through: :bookmarks

    validates :title, presence:true
    validates :overview, presence:true
    validates :title, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
    before_action :set_list, only: %i[new create]

    def new
      @bookmark = Bookmark.new
    end

    def create
      @bookmark = Bookmark.new(bookmark_params)
      @bookmark.list = @list
      if @bookmark.save
        redirect_to list_path(@list)
      else
        render :new, status: :unprocessable_entity
      end
    end

    def destroy
      @bookmark = Bookmark.find(params[:id])
      @bookmark.destroy
      redirect_to list_path(@bookmark.list), status: :see_other
    end

    private

    def set_list
      @list = List.find(params[:list_id])
    end

    def bookmark_params
      params.require(:bookmark).permit()
    end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
    before_action :set_list, only: %i[ show edit update destroy ]

    def index
      @lists = List.all
    end

    def show
    end

    def new
      @list = List.new
    end


    def edit
    end


    def create
      @list = List.new(list_params)

      if @list.save
        redirect_to @list, notice: "Article was successfully created."
      else
        render :new, status: :unprocessable_entity
      end
    end

    def update
      if @list.update(list_params)
        redirect_to @list, notice: "Photos was successfully updated."
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @list.destroy
      redirect_to root_path, notice: "Photo was successfully destroyed."
    end

    private

    def set_list
      @list = List.find(params[:id])
    end

    def list_params
      params.require(:list).permit(:title, :body, photos: [])
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
    def index
        @movies = Movie.all
      end

      def show
        @movie = Movie.find(params[:id])
      end

      def new #render the form
        @movie = Movie.new
      end

      def create

        @amovie = Movie.new(movie_params) #more secure than above with a hash

        if @movie.save
          redirect_to @movie
        else
          render :new, status: :unprocessable_entity
        end
      end

      def edit
        @movie = Movie.find(params[:id])
      end

      def update
        @movie = Movie.find(params[:id])

        if @movie.update(movie_params)
          redirect_to @movie
        else
          render :edit, status: :unprocessable_entity
        end
      end

      def destroy
        @movie = Article.find(params[:id])
        @movie.destroy

        redirect_to root_path, status: :see_other
      end

      private
        def movie_params
          params.require(:movie).permit(:title, :overview, :poster_url, :rating)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/_form.html.erb
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.submit class: 'btn btn-primary my-4' %>
<% end %>

app/views/bookmarks/edit.html.erb
<h1>Edit Boomark</h1>

app/views/bookmarks/index.html.erb
<h1>My bookmark</h1>
<%= render "form" %>

app/views/bookmarks/new.html.erb
<h1>New Bookmark</h1>

<%= render "form", bookmark: @bookmark %>
<%= link_to "Back", movies_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for(@list) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <%= f.input :photos, as: :file, input_html: { multiple: true } %>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/lists/_list.html.erb
<div id="<%= dom_id list %>">
  <p>
    <strong>Title:</strong>
    <%= list.name %>
  </p>
</div>

app/views/lists/edit.html.erb
<h1>Editing Photos</h1>

<%= render "form", list: @list %>

<br>

<div>
  <%= link_to "Show photos of list", @list %> |
  <%= link_to "Back to lists", root_path %>
</div>

app/views/lists/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>List</h1>

<div id="lists">
  <% @lists.each do |list| %>
    <%= render list %>
    <p>
      <%= link_to "Show this list", list %>
    </p>
  <% end %>
</div>

<%= link_to "New List Photo", new_list_path %>

app/views/lists/new.html.erb
<h1>New Photos</h1>

<%= render "form", list: @list %>

<br>

<div>
  <%= link_to "Back to fotos", list_path %>
</div>

app/views/lists/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @list %>

<% @list.photos.each do |photo| %>
  <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %>
<% end %>

<div>
  <%= link_to "Edit this list", edit_list_path(@list) %> |
  <%= link_to "Back to list", root_path %>

  <%= button_to "Destroy this list", @list, method: :delete %>
</div>

app/views/movies/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">BLUE START CINEMA</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <button class="btn btn-outline-success" type="submit">My list</button>
        <button class="btn btn-outline-success" type="submit">New list</button>
      </form>
    </div>
  </div>
</nav>

app/views/movies/index.html.erb
<%= render "navbar" %>

<div id="banner">
  Films
</div>

<h1>My movies</h1>

<ul>
    <% @movies.each do |movie| %>
        <li>
          <%= movie.title %>
        </li>
    <% end %>
</ul>

<div>
  <div class="d-grid gap-2">
    <button class="btn btn-success" type="button">Create a Movie List</button>
  </div>
</div>